# Source: manifests/kpt-probe-daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kpt-probe
  namespace: {{ .Release.Namespace }}
  labels:
    app: kpt-probe
spec:
  selector:
    matchLabels:
      app: kpt-probe
  template:
    metadata:
      labels:
        app: kpt-probe
    spec:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: kpt-probe
        image: {{ .Values.kptProbe.image }}
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          allowPrivilegeEscalation: true
          capabilities:
            add:
              - NET_ADMIN
              - SYS_ADMIN
              - SYS_RESOURCE
              - IPC_LOCK
        resources:
          limits:
            memory: {{ .Values.kptProbe.resources.limits.memory | quote }}
            cpu: {{ .Values.kptProbe.resources.limits.cpu | quote }}
          requests:
            memory: {{ .Values.kptProbe.resources.requests.memory | quote }}
            cpu: {{ .Values.kptProbe.resources.requests.cpu | quote }}
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KPT_VISOR_SERVICE
          value: "kpt-visor.{{ .Release.Namespace }}.svc.cluster.local:8080"
        volumeMounts:
        - name: host-root
          mountPath: /host
          readOnly: true
        - name: sys
          mountPath: /sys
          readOnly: false
        - name: modules
          mountPath: /lib/modules
          readOnly: true
        - name: bpf
          mountPath: /sys/fs/bpf
          readOnly: false
        - name: host-netns
          mountPath: /var/run/netns
          readOnly: true
        - name: ovs-socket
          mountPath: /var/run/openvswitch
          readOnly: false
        - name: cgroup
          mountPath: /sys/fs/cgroup
          readOnly: true
        - name: debugfs
          mountPath: /sys/kernel/debug
          readOnly: false
        ports:
        - name: http
          containerPort: 8081
          protocol: TCP
      hostNetwork: true
      volumes:
      - name: host-root
        hostPath:
          path: /
      - name: sys
        hostPath:
          path: /sys
      - name: modules
        hostPath:
          path: /lib/modules
      - name: bpf
        hostPath:
          path: /sys/fs/bpf
      - name: host-netns
        hostPath:
          path: /var/run/netns
      - name: ovs-socket
        hostPath:
          path: /var/run/openvswitch
          type: Directory
      - name: cgroup
        hostPath:
          path: /sys/fs/cgroup
      - name: debugfs
        hostPath:
          path: /sys/kernel/debug
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      serviceAccountName: kpt-probe-sa
