# Source: manifests/kpt-visor-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kpt-visor
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: kpt-visor
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
