# Source: manifests/kpt-probe-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kpt-probe
  namespace: {{ .Release.Namespace }}
  labels:
    app: kpt-probe
spec:
  selector:
    app: kpt-probe
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  clusterIP: None
