apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kptmonitors.kpt.kubeseek.com
spec:
  group: kpt.kubeseek.com
  names:
    kind: KptMonitor
    listKind: KptMonitorList
    plural: kptmonitors
    singular: kptmonitor
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - namespace
                - targetPods
                - tapDuration
              properties:
                namespace:
                  type: string
                  description: "Namespace specifies the namespace where target pods are located"
                targetPods:
                  type: string
                  description: "TargetPods specifies the pods to be monitored"
                tapDuration:
                  type: string
                  description: "TapDuration specifies the duration for monitoring"
            status:
              type: object
              properties:
                status:
                  type: string
                  description: "Status indicates the current status of the monitoring"
                lastUpdated:
                  type: string
                  format: date-time
                  description: "LastUpdated is the timestamp when the status was last updated"
      subresources:
        status: {}
      additionalPrinterColumns:
        - name: Namespace
          type: string
          jsonPath: .spec.namespace
        - name: TargetPods
          type: string
          jsonPath: .spec.targetPods
        - name: TapDuration
          type: string
          jsonPath: .spec.tapDuration
        - name: Status
          type: string
          jsonPath: .status.status
        - name: Age
          type: date
          jsonPath: .metadata.creationTimestamp
